### ISSUE TITLE
Retrieve header information

### ISSUE THREAD

**Issue by vialcollet** [umanamente/n8n-nodes-imap#16]
Hi

I don't see message header in the retrieved data.
Is there a plan to add it?
It can be very useful to classify emails and identify spams for example.

In the core imap node we have fields such as:
- metadata/content-type
- metadata/received
- metadata/return-path
- metadata/authentication-results
- ...

Thanks

**Comment by umanamente** [comment]
Added option to include email headers in [v1.3.0](https://github.com/umanamente/n8n-nodes-imap/releases/tag/v1.3.0)

**Comment by vialcollet** [comment]
Fantastic, tested ok!
Thanks a lot
