### ISSUE TITLE
mail_max_userip_connections

### ISSUE THREAD

**Issue by vialcollet** [umanamente/n8n-nodes-imap#17]
Hi
When using the node I reach the limit of maximum active connections per user and per IP.  
I increased it on my mail server but it seems that the node doesn't close connections properly.  
Any idea on how to resolve this?

![image](https://github.com/umanamente/n8n-nodes-imap/assets/4971086/3c98e0e0-d823-462b-aa1b-52e43ae93335)

**Comment by umanamente** [comment]
Please update to  [v1.3.0](https://github.com/umanamente/n8n-nodes-imap/releases/tag/v1.3.0) and check if the problem is resolved. It is likely that this update has fixed the issue

**Comment by vialcollet** [comment]
After updating to v1.3.0 and a few hours of tests, no more issue.  
Now the connection closes gracefully.

thanks a ton
