### ISSUE TITLE
n8n-nodes-imap package is gone after reload of n8n

### ISSUE THREAD

**Issue by Disane87** [umanamente/n8n-nodes-imap#21]
I installed yopur package in the latest version of n8n (running in a docker container). Installation works but if I add a node to a worklow and reopen the node, n8n says the package isn't installed:
![image](https://github.com/umanamente/n8n-nodes-imap/assets/956158/a3d9a4f0-037a-45f9-9490-d97f2ff64d61)

Additionally I have the same issue as described in #15. Even a restart of the docker container doesn't work. I can't add any creds. I also added "Basic Auth" creds manually but they won't show up.

My workflow should be triggered by schedule and auto archive mails wich are older than x days. So my workflow isn't that big atm:

![image](https://github.com/umanamente/n8n-nodes-imap/assets/956158/b751e607-f44e-4d62-baca-93df4bd1e918)

**Comment by umanamente** [comment]
It seems like N8N problem. Please report this problem on [N8N forum](https://community.n8n.io/c/questions/12) and share the topic URL with me. I'll monitor it as well.

**Comment by Disane87** [comment]
Weird, after some time waiting it's now working properly. You can consider this as closed :)

**Comment by paulwer** [comment]
we discovered, that this is a caching problem within the browser, after a restart of n8n and clearing the browser cache it worked fine.
