### ISSUE TITLE
Credentials not found

### ISSUE THREAD

**Issue by axute** [umanamente/n8n-nodes-imap#22]
I have created the login data and tested it, it works.
If I enter "INBOX" in the path, it works, but the autocompletion doesn't work, it says it doesn't have any credentials. Cache is disabled.

![image](https://github.com/umanamente/n8n-nodes-imap/assets/641986/a9a7c0c6-dd9c-43ff-bfee-50422ff4b9a2)

**Comment by umanamente** [comment]
Which IMAP server are you using?
Could you try with another IMAP server (gmail, yahoo, etc)?

**Comment by axute** [comment]
I use mailcow with self signed certificate, it is a public known selfhosted mailserver solution.
Sorry, I can't test with another account.

The E-Mail-Trigger works fine with same credentials.

**Comment by syberx** [comment]
same i use mailcow with self signed .. i get error: Error details

 Other info
Node type

n8n-nodes-imap.imap

Node version

1 (Latest)

n8n version

1.48.3 (Self Hosted)

Time

11.7.2024, 10:46:33

Stack trace

NodeApiError: Unable to set flags, unknown error at Object.executeImapAction (/.n8n/nodes/node_modules/n8n-nodes-imap/nodes/Imap/operations/email/functions/EmailSetFlags.ts:106:15) at processTicksAndRejections (node:internal/process/task_queues:95:5) at Object.execute (/.n8n/nodes/node_modules/n8n-nodes-imap/nodes/Imap/Imap.node.ts:152:28) at Workflow.runNode (/usr/lib/node_modules/n8n/node_modules/n8n-workflow/src/Workflow.ts:1378:8) at /usr/lib/node_modules/n8n/node_modules/n8n-core/src/WorkflowExecute.ts:1059:27 at /usr/lib/node_modules/n8n/node_modules/n8n-core/src/WorkflowExecute.ts:1762:11

**Comment by umanamente** [comment]
Fixed in **v2.0.1**
