### ISSUE TITLE
Add custom flags

### ISSUE THREAD

**Issue by syberx** [umanamente/n8n-nodes-imap#23]
Hey i can add many Flags seen,answerd ...

But i need to add custom flags..

example python: 
mail.uid('store', uid, '+FLAGS', 'paperless')

can you add custom flags ? I can see this flags in my android app and thunderbird. I can see label "paperless"

Big Thanks !!

**Comment by umanamente** [comment]
Unfortunately, adding custom flags is not widely supported by IMAP servers and might confuse users or cause unexpected bugs. Standard flags like \Seen are part of the RFC specifications, while custom flags are not supported by most commonly used servers such as Gmail and MS Exchange.

**Comment by syberx** [comment]
and "flagColor" ? Nexcloud add this to important mail. Or do you have an idea how I can do it myself? Or maybe a custom code field? Where everyone can add their own stuff without having to "select". That shouldn't cause any problems, right?

**Comment by umanamente** [comment]
"\Flagged" is usually used for important mail
