### ISSUE TITLE
Feature Request: Save Draft to Mailbox

### ISSUE THREAD

**Issue by paulwer** [umanamente/n8n-nodes-imap#24]
Hi,
we are looking for a solution, to save a new draft into the mailbox, to preformulate answers by an n8n ai model and place them into the mailbox afterwards.

According to our research, this could be done with the imap APPEND command: https://www.rfc-editor.org/rfc/rfc3501#section-6.3.11
(hope we got this right)

Would it be able to add an action into this node, supporting this in a conveniant way?

Thank you very much for your work so far and have a nice day :)

**Comment by umanamente** [comment]
"create draft" operation added in v2.1.0

**Comment by paulwer** [comment]
very much thank you.
