### ISSUE TITLE
Problem? with move email module

### ISSUE THREAD

**Issue by VMAJSTER** [umanamente/n8n-nodes-imap#25]
Hello,

first of all, I would like to write that I do not know if it is a mistake in my flow or if this is how the module is designed, hence my issue

![image](https://github.com/user-attachments/assets/0adbd68d-8268-4324-8596-4c3ed87f4b30)

When i read mails from mailbox for ex. 50 emails which, after match the if rule, go to the move module, but i got error message, and only one message is moving

![image](https://github.com/user-attachments/assets/930de3e8-d640-4841-9bb2-25218b934fa0)

It should be like that and i must use loop?

![image](https://github.com/user-attachments/assets/6063d2ce-f54b-4a0a-8bb3-9fecda87dc8c)

instead thanks for create this package- it is 100% much better than default

Regards,
Daniel

**Comment by umanamente** [comment]
I couldn't reproduce the issue. I didn't use a loop; the first approach should be fine. It might be a temporary problem with the IMAP server.

Does it work when using a loop?

**Comment by VMAJSTER** [comment]
unfortunately I also get an error when using the loop

I assume that the problem is on the server side, because for example on another test box it seems to be fine

strange, i will have to think of a solution
