### ISSUE TITLE
Feature Request: Retrieve mail by UID

### ISSUE THREAD

**Issue by mendoncart** [umanamente/n8n-nodes-imap#34]
Hello!

First of all, your node saved me—thank you!

Now, regarding my feature request: I’d like to use something similar to the "Get Many" function, but for a specific email.

Currently, I'm storing the UID on a button and sending it through a chatbot. When the button is pressed (e.g., "move email"), I can retrieve the UID from that button and use it to manipulate the email.

However, when I need more information about the same email (such as headers, content, sender, etc.), there's no way to retrieve it using only the UID.

It would be great if it were possible to retrieve the same information that the "Get Many" function provides.

**Comment by mendoncart** [comment]
Or, if it's easier, to include a "UID Is", or "UID Contains" option on Filter:
![image](https://github.com/user-attachments/assets/359ecc3f-beae-46c5-bdef-e3b5fc0e47c3)

**Comment by umanamente** [comment]
Implemented in v2.4.0

**Comment by mendoncart** [comment]
Worked like a charm!!! Thank you!
