### ISSUE TITLE
Move single email not working

### ISSUE THREAD

**Issue by gamersalpha** [umanamente/n8n-nodes-imap#35]
Hello there, 

so i installed n8N with n8n-imap node : 

![image](https://github.com/user-attachments/assets/18c44bd7-1c07-4fc1-a5ab-36e7ab41458b)

si i create a node imap move mail andi push the UID of the mail : 

![image](https://github.com/user-attachments/assets/a8a38ba4-4ed2-4555-b59f-4111e3efd0b6)

but when i lunch it, all the mail of the folder mailbox is moved on the same folder and the selection of the mail is not working

how fix this problem please

**Comment by umanamente** [comment]
Can you provide more details? Please share info from the previous nodes and the result of this one. What did you expect to happen, and what actually happened? Attach some screenshots if possible.

**Comment by gamersalpha** [comment]
Hello, 

this my graph : 

![image](https://github.com/user-attachments/assets/6ee5b69c-87fd-4832-ae7c-d978c137c6c7)

the problem come from here : 

![image](https://github.com/user-attachments/assets/7b4a0d83-b6c0-4f27-ba4d-5204a8f4cdc8)

Like u see in 1 i got only mail i want moved with a selection by from in the swtich case : 

![image](https://github.com/user-attachments/assets/3c63908b-2c76-41d1-8fbe-aa055a1a1d46)

this switch case get 3 out, with select on form 

looks like working 

but the problem is the  imap 2 node move détails : 

![image](https://github.com/user-attachments/assets/a9ed567a-867f-4077-bf7a-7930dcf14c6b)

In the first using, all mail from inbox are moving and not only the mail with UID  i got on the node

this a my bug, i can't move only one mail, the node move all mail from Source Mailbox From LIST on the destination Mailbox


why i can't move only one mail i select and not all mail from the source folder

thanks

**Comment by gamersalpha** [comment]
u need more information ?

**Comment by umanamente** [comment]
I couldn't reproduce the problem on my end; I tested on my server, and emails are moving as expected. 

However, I noticed that you have the IMAP node output looped back into its input. Could you clarify why this setup is in place? Please try removing that connection and testing again—it might be causing the issue.
