### ISSUE TITLE
move multiple mails

### ISSUE THREAD

**Issue by jacekjaros** [umanamente/n8n-nodes-imap#5]
Hi,

i have simple workflow

![Screenshot 2024-02-13 at 12 53 52](https://github.com/umanamente/n8n-nodes-imap/assets/5748557/3e345f43-252d-4344-a13e-71857741f817)

Even if multiple emails is passed to move email block only first will be processed. Is this expected?

**Comment by umanamente** [comment]
Yes, there is a bug. Only first item is processed for any operation. I will fix it.

**Comment by umanamente** [comment]
@jacekjaros, thank you for reporting the problem. The issue is fixed, please update the node (n8n restart is required) and confirm if everything is working as expected on your end.
